# SwiftLint Configuration for MediTimer
# See https://realm.github.io/SwiftLint/rule-directory.html for all rules

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Enable opt-in rules for stricter quality
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules (we want strict quality)
disabled_rules:
  - todo # Allow TODOs during development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - url
    - i
    - x
    - y

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
    error: 50

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: warning

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  MediTimer
                    \/\/

# Custom reporter (use 'xcode' for Xcode integration)
reporter: "xcode"
